### ISSUE TITLE
How to get the server welcome message after connecting?

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-irc#2]
The server welcome message appears in the Sockethub logs, but it seems like there's no way to get it in the client.

Same goes for any server message for that matter...

**Comment by silverbucket** [comment]
If I remember correctly, there is a dead-zone after register but before the full listener handlers are registered, where these initial server messages come through, containing MOTD etc.

The temp handler is here:
https://github.com/sockethub/sockethub-platform-irc/blob/master/index.js#L164-L166

We can figure out a format, and what data we want to send back, and then it should be simple to add the code. Related to #1

**Comment by skddc** [comment]
Cool, let's do it!

The format for server messages is just text, no?

**Comment by silverbucket** [comment]
I'm wondering what the actor object would look like? It comes straight from the server, so I'm wondering what the object @type should be. I don't think `server` makes sense,  as there can be more than one thing hosted on a server, but maybe `service`?

So, we'd have something like:

```
{
  "@type": "send",
  "context": "irc",
  "actor": {
    "@id": "irc://irc.freenode.net",
    "@type": "service",
    "displayName": "irc.freenode.net"
  },
  "object": {
    "@type": "message",
    "content": "..."
  },
  "target": {
    "@id": "irc://foobar@irc.freenode.net",
    "@type": "person",
    "displayName": "Foobar McUser"
  }
}
```

**Comment by skddc** [comment]
Why not `server`? Isn't that what we have `"@context": "irc"` for?

**Comment by silverbucket** [comment]
i dont understand what you mean. can you elaborate?

**Comment by skddc** [comment]
> I don't think server makes sense, as there can be more than one thing hosted on a server, but maybe service?

The other things would have a different context then, so why can't we user `server`?

**Comment by silverbucket** [comment]
I didn't mean in the realm of AS, I meant just in general, the word `server` is often over-used where `service` is more specific. 

But to address your point. The `context` is the way of grouping related objects, the `@type`, when used within `object`, `target`, or `actor` is the actual entity we're interacting/dealing with. Whether it be a `message`, `room`, `person` or `service`.

So, `irc->service` makes sense like `irc->room` and `irc->person`. Service seems more broadly applicable to other contexts where similar things might be the case. But in the end it's really about whether you consider a piece of software running on a server to also be called a server. In some cases people have used the word server, but I think in all cases the term service still makes sense, and applies to the concept in general.

**Comment by silverbucket** [comment]
Actually I just looked up the activity streams draft and they list `Service` as well.
http://www.w3.org/TR/activitystreams-core/#actor

**Comment by skddc** [comment]
> Service seems more broadly applicable to other contexts

Why should it be applicable to other contexts? With IRC, as a server/client protocol, it's definitely a "server", so naming it "service" is just confusing in the IRC context. And as we have our own `@context` for IRC anyway, shouldn't we name things the way they are actually named in both the spec as well as colloquial language?

Regarding the AS draft: it doesn't list "channel" either, and the links to both the vocabulary are 404. :(

Anyway, if these AS objects should represent real-world things, then I'd propose to use familiar naming, so that the module API is both clear and intuitive.

P.S.: Even if it gets a different name in the end, that shouldn't keep us from adding support for server messages in general.

**Comment by silverbucket** [comment]
It's not about naming things based on the services for each and every `context` (also not the same as `@context` - the @context is what defines the vocabulary, not the `context` which is just a way of grouping related objects).

The benefit of the vocabulary is not to create a context for, say, IRC and then name everything based on IRC terms. It's to use a layer of abstraction, which is what AS2.0 vocabulary is. That's why a `channel` is called a `room` in sockethub, because it's not about mapping to IRC names, where in XMPP it'd be named something else. Or using `nick` instead of `person`, that's missing the point.

In this case, we are defining a new object type. This object type should be applicable to more than /just/ IRC unless IRC is the only thing that exists which this concept, which is not the case. There are many situations when interacting with an API where you are not talking to a person or chatroom on the other end, but dealing directly with the service (or it is interacting with you).

**Comment by skddc** [comment]
Alright. It's less clear and intuitive, but makes sense to me then.

**Comment by skddc** [comment]
Closing on favor of #5.
