### ISSUE TITLE
NickServ/ChanServ messages

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-irc#3]
As proposed by @silverbucket in https://github.com/sockethub/sockethub-platform-irc/issues/1#issuecomment-104315113 we should probably treat it as a normal message to a "user":

```json
{
  "@type": "send",
  "context": "irc",
  "actor": "",
  "target": {
    "@id": "irc://NickServ@irc.freenode.net",
    "@type": "service"
  },
  "object": {
    "@type": "message",
    "content": "identify Password1234"
  }
}
```

**Comment by silverbucket** [comment]
If I'm not forgetting/overlooking something, this *should* already work.

**Comment by skddc** [comment]
Oh, so direct messages already work, when just using the user instead of a channel as target?

**Comment by silverbucket** [comment]
It should, I mean, the mechanics are exactly the same. So the platform should just write the msg to NickServ as if they are user.

**Comment by silverbucket** [comment]
One thing that would be nice is, when receiving responses from things like `NickServ` it would be good to have something in the IRC protocol that defines the incoming message as from a non-human. That way the platform can set the `@type` as `service` instead of `person` when it sends the reply back to the app. 

If you try this, can you paste the console log message response so we can check it for unique meta data.

**Comment by skddc** [comment]
Ok.

**Comment by skddc** [comment]
Closing for now. I'll either re-open or create a new issue depending on how it goes.
